triggers:
- envs: []
  last_enabled_at: 2024-02-08 19:12:13.017222
  name: green_taxi_etl_trigger
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-02-08 05:00:00
  status: active
  variables: {}
